### ISSUE TITLE
Dependency issues in Devograph stage 1 pipeline

### ISSUE THREAD

**Issue by sushmanthreddy** [DevoLearn/DevoGraph#1]
- There is problem with devograph stage 1 pipeline while extracting centroids of cell  from devograph stage 1 pipeline there is an dependency issues of devolearn encountering !

-  There are lot of deprecated libraries are been used for devolearn these are making problem ,while we run the colab notebook of devograph of stage 1 ..And libraries for these should be updated in devolearn requirements.txt file for smooth movement  in stage1 pipeline of devograph ..These are following errors I have encountered while running stage 1 pipe line

<img width="937" alt="Screenshot 2023-01-28 at 11 51 35 PM" src="https://user-images.githubusercontent.com/73489688/215509372-0b2c148e-6624-481d-82df-23423adc400e.png">

- The issue can be reproduced by running devograph stage 1 colab notebook  [`link`](https://github.com/DevoLearn/DevoGraph/blob/main/stage_1/stage_1.ipynb) in colab

**Comment by crsdvaibhav** [comment]
I would really love to solve this issue, could you assign this to me? Thanks!

**Comment by sushmanthreddy** [comment]
@crsdvaibhav go ahead and start working on it....
